// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_nEn2jWGBa8zmCgv9nsu4_tREDTieOQ',
    appId: '1:498154989418:web:81056807223df0b62ce713',
    messagingSenderId: '498154989418',
    projectId: 'tinderdating-399bd',
    authDomain: 'tinderdating-399bd.firebaseapp.com',
    storageBucket: 'tinderdating-399bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEd1m5L2QbqGZa5G_ociJ120JHvALVfp4',
    appId: '1:498154989418:android:7aeb8724f457b49f2ce713',
    messagingSenderId: '498154989418',
    projectId: 'tinderdating-399bd',
    storageBucket: 'tinderdating-399bd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK_nEn2jWGBa8zmCgv9nsu4_tREDTieOQ',
    appId: '1:498154989418:web:56a42b07d1e90a992ce713',
    messagingSenderId: '498154989418',
    projectId: 'tinderdating-399bd',
    authDomain: 'tinderdating-399bd.firebaseapp.com',
    storageBucket: 'tinderdating-399bd.firebasestorage.app',
  );
}
